### ISSUE TITLE
Termux issue 

### ISSUE THREAD

**Issue by The-Jester12** [zombifications/phosint#1]
I get this error code even though I did pip install -r requirements.txt 
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/data/data/com.termux/files/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/data/com.termux/files/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/phosint/phosint.py", line 90, in <module>
    main()
  File "/data/data/com.termux/files/home/phosint/phosint.py", line 79, in main
    caller_id(sys.argv[1])
  File "/data/data/com.termux/files/home/phosint/phosint.py", line 28, in caller_id
    resp = requests.post("https://api.calleridtest.com/freebie", json={"number": number}).json()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by drooling** [comment]
calleridtest.com added CloudFlare protection to that endpoint, in the source I have handled the exception accordingly. Please update the main.py file and try again.

**Comment by The-Jester12** [comment]
~/phosint $ ls
README.md  phosint.py  requirements.txt
Ls didn't reveal a main.py file

**Comment by The-Jester12** [comment]
Ls never revealed a main.py file
~/phosint $ ls
README.md  phosint.py  requirements.txt
